name: Build PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      
    - name: release.sh
      uses: dante-ev/latex-action@latest
      with:
        entrypoint: ./build.sh
